version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "punbot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fhz5egdnfy2n"
s3_prefix = "punbot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

